### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by emartynov** [getsentry/raven-objc#51]
Hi guys,

Thanks for the library. We use it for some error logging on mobile platforms.

I've looked into the code and see that errors will be lost if device is offline. It is not rare situation when mobile device is offline.

Do you think about supporting offline?

**Comment by asbjornu** [comment]
Hi. I'm not sure what offline support you need that the library currently doesn't offer. You have the `sendNow:(BOOL)sendNow` parameter of `- (void)captureMessage:` that you can set to `NO` if you want the message stored on disk and sent later. Is this not sufficient?

**Comment by emartynov** [comment]
It is something but not really sufficient.

It will try to send reports on the next ```setupExceptionHandler``` which also will not send data if device is offline.

**Comment by asbjornu** [comment]
Seems like #52 solves that problem. Can you clone/merge and see if it does, @emartynov?

**Comment by emartynov** [comment]
I think it is step towards. Thank you! but default implementation is not saving data for us.

**Comment by asbjornu** [comment]
Which default implementation are you talking about, @emartynov? @toolboxash's fork?

**Comment by emartynov** [comment]
Yes, the changes are adding opportunities to handle success or failure. But by default it is not doing anything. I think we can close this issue. And I will continue on the pull request

**Comment by asbjornu** [comment]
I see. Yea, let's continue the discussion there. Thanks! :)

**Comment by toolboxash** [comment]
My fork was just a merge of another fork by sbelpa who was responsible for the original implementation.
I just merged it into the latest in the main branch and sent the pull request.

I think the error case is not handled because the external interface does not support passing errors.

There are 4 ways we could deal with the empty error case.

1. Extend the external interface to add methods that pass an optional error block
2. Keep the interface the same and add a method to register a default error callback
3. Broadcast a notification if an error is received
4. Leave it as it currently does and ignore it

The interface is intended to be a fire and forget so I would probably discount option 1 and 2.

Option 3 might be a good compromise.

I left it as option 4 because that was enough for my needs.

Ash

**Comment by toolboxash** [comment]
It may also be worth implementing a mechanism to handle re-tries so that an event is deleted after a number of failed retries.

I also think flushing the events on a reachability update is also wroth implementing
