### ISSUE TITLE
Not working for global exception handling

### ISSUE THREAD

**Issue by tapannathvani** [getsentry/raven-objc#56]
Hello,

I am not getting crash log on my sentry account.
I also restarted/relaunch my application multiple times.

This is how i am implementing it on my iOS app

RavenClient *client = [RavenClient clientWithDSN:@"https://XXXXXX:XXXXX@sentry.abc.com/123"];
[RavenClient setSharedClient:client];
[[RavenClient sharedClient] setupExceptionHandler];

**Comment by timorzadir** [comment]
If you change DSN in the example project, do you get logging? 
I tested the example project both in simulator and device now, and both environment logs to Sentry.

**Comment by ryanio** [comment]
+1, and I think the same issue is present in #54

I'm using iOS 8.3 / Swift 1.2, not sure if that makes a difference. Any way I can help debug further?

**Comment by tapannathvani** [comment]
@ryanio Yes you are right, manually exceptions working fine but global exception doesnt work for me.

**Comment by timorzadir** [comment]
@ryanio, @tapannathvani I do not believe #54 is related, as it seems to be an issue with using the NSSetUncaughtExceptionHandler on OSX. 

@tapannathvani: Have you tried the example project? 
Are you using the 1.0.1 release or older? 

If you can provide us with an example project with non-functional exception handling, I would be happy to have a look at it.

**Comment by starlabs007** [comment]
I've been encountering this issue on a Swift-centric project. CaptureMessage works but the global exception handler never gets called. I think I've found out why: a good majority of crashes on Swift apps occur when a nil optional is unwrapped - and that was the test case I was using Sentry against (although I believe this issue will apply to all iOS apps, Swift or not).

As it turns out this type of error does NOT generate an exception, but a signal. See here:
http://stackoverflow.com/questions/1128539/nssetuncaughtexceptionhandler-not-catch-all-errors-on-iphone

As a test I modified RavenClient.m locally (as per the link in the answer) to catch signals and it works.

Note: running the app through Xcode will prevent the signal handlers from firing, as it captures these errors and never passes them to the app. Running the app on-device or in the simulator without Xcode does allow the signal handlers to get called.

**Comment by timorzadir** [comment]
Great findings @starlabs007. Do you have code that you would like to share with us in a PR?

**Comment by starlabs007** [comment]
@timorzadir Unfortunately I don't have the code anymore as it was for testing and I reverted my changes. Most were just copy and pasted (with modifications to make it work) from these two articles:
https://creativeinaustria.wordpress.com/2008/10/20/crash-reporter-for-iphone-applications-part-2/
http://www.cocoawithlove.com/2010/05/handling-unhandled-exceptions-and.html

I put this (as per the article) in the setupExceptionHandler block (after NSSetUncaughtExceptionHandler got called):
```objectivec
        struct sigaction mySigAction;
        mySigAction.sa_sigaction = mysighandler;
        mySigAction.sa_flags = SA_SIGINFO;
        sigemptyset(&mySigAction.sa_mask);
        sigaction(SIGQUIT, &mySigAction, NULL);
        sigaction(SIGILL, &mySigAction, NULL);
        sigaction(SIGTRAP, &mySigAction, NULL);
        sigaction(SIGABRT, &mySigAction, NULL);
        sigaction(SIGEMT, &mySigAction, NULL);
        sigaction(SIGFPE, &mySigAction, NULL);
        sigaction(SIGBUS, &mySigAction, NULL);
        sigaction(SIGSEGV, &mySigAction, NULL);
        sigaction(SIGSYS, &mySigAction, NULL);
        sigaction(SIGPIPE, &mySigAction, NULL);
        sigaction(SIGALRM, &mySigAction, NULL);
        sigaction(SIGXCPU, &mySigAction, NULL);
        sigaction(SIGXFSZ, &mySigAction, NULL);
```

One issue I had with my test was the signal handler was firing way too many times from just one error. Not sure what the issue was. My ObjC experience is minimal, so I was unable to troubleshoot it any further (and ran out of time).

**Comment by tapannathvani** [comment]
I placed my DSN into your example project but still it didnt work for me...

**Comment by tompark-IO** [comment]
I'm having this issue with nil-optional related crashes not reporting as well.

**Comment by Kowaio** [comment]
Hello,
I'm following up here as I'm making an app using only Swift 2. All the capture messages are correctly reported to sentry using my DSN but crashes don't seem to be. Is there a workaround since last may on that matter?
Thanks guys.
Best,

**Comment by dcramer** [comment]
The current Objective-C client was never really supported well by the Sentry server, and we're aiming to fix that in Q1 of this year with a brand new Swift client.

**Comment by Kowaio** [comment]
Oh! That's great to know! Thanks for the update and keep up the good work :)

**Comment by timorzadir** [comment]
@dcramer Will the brand new client be written from scratch with any new functionality, or based on [Raven-swift](https://github.com/getsentry/raven-swift)?

**Comment by dcramer** [comment]
@timorzadir it might leverage some things that exist in the current codebase, but atm its being built from scratch. We're relying on some existing tools, so it's primarily just an API layer on top of another SDK.

**Comment by HiveTraum** [comment]
When you planing to release it?

**Comment by dcramer** [comment]
We will release it when its at a point to show the public.

**Comment by HiveTraum** [comment]
i think i found solution, use it like that:
`RavenClient *client = [RavenClient clientWithDSN:@"http://..."];
    [RavenClient setSharedClient:client];
    [[RavenClient sharedClient] setupExceptionHandler];`
not like that:
``RavenClient *client = [RavenClient clientWithDSN:@"http://..."];
    [[RavenClient sharedClient] setupExceptionHandler];
    [RavenClient setSharedClient:client];``

**Comment by pnull** [comment]
Any news on this? :-)

**Comment by dcvz** [comment]
@dcramer this is a product that businesses use and pay for, if a new framework is underway that is fine, but don't stop supporting the current ones in hope that the new framework will fix all the issues. Issues that are clear here and now are not being addressed just because a new framework (which has taken months now) is underway.

**Comment by dcramer** [comment]
@dcvz we did not build this SDK nor have we (sentry the business) ever supported it officially. We have full iOS support on getsentry.com in beta so if that's of interest contact support and we'll get you access.

**Comment by asbjornu** [comment]
@dcvz It might be worth mentioning here that @timorzadir and I did "support" this library for a while until @dcramer [told us](#issuecomment-174578817) that they were working on a new library. Since then, we haven't really seen the point of investing time and energy on something that is going to be replaced.

**Comment by dcramer** [comment]
Just going to close these out. We'll announce public release soon of iOS, but as mentioned contact us if you have questions. It requires you to push dSYMs to us which is only visible to organizations flagged as early adopter (in org settings on getsentry.com).

The two new repos:

http://github.com/getsentry/sentry-swift
http://github.com/getsentry/sentry-objc

(We have an Obj-C client yet due to Unity's requirements, but Swift is the preferred library)

**Comment by MihaelIsaev** [comment]
Still didn't work for me in Swift 2.2 project. I tried to make crashes on device without connection to Xcode, but crashes never sends. Only manual crashes successfully sends.

**Comment by dcramer** [comment]
@MihaelIsaev please use sentry-swift, and if you have any issues with it report them via that issue tracker.
